
#Project Name
name: 'northwind'
version: '1.0.0'
config-version: 2

# dbt profile
profile: 'northwind'


# paths for each resourse
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# directory for compiled SQL files
target-path: "target"  

# dbt clean
clean-targets:
  - "target"
  - "dbt_packages"
  - logs

# Configuring models
models:
  northwind:
    staging_model:
      +materialized: view
      +schema: staging
      +enabled: true
    warehouse_model:
      +materialized: table
      +schema: warehouse
      +enabled: true
    analytics_obt_model:
      +required_docs: true # dbt run-operation required_tests   
      +required_tests: {"unique.*|not_null": 1} # # dbt run-operation required_tests  
      +materialized: table
      +schema: analytics_obt
      +enabled: true

